name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repo Clone
        uses: actions/checkout@v4
      - name: Compile
        run: mvn compile
      - name: Package
        run: mvn package
      - name: Clean up the mess
        run: mvn clean
