name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repo Clone
        uses: actions/checkout@v4
      - name: Compile
        run: mvn compile
      - name: Package
        run: mvn package
      - name: Test Packages
        run: |
          java -jar iot-server/target/iot-server-1.0.jar
          java -jar iot-device/target/iot-device-1.0.jar
      - name: Clean up the mess
        run: mvn clean
